---
title: "Trabalho 1"
author: "Roubean Gomes"
date: "28/08/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Trabalho Estatistica Descritiva

Trabalho de Estatistica Descritiva que apresent dados e graficos 

```{r}
library(readxl)
library(tidyverse)
library(ggplot2)
HiperUFSC_Dataset <- read_excel("C:/Users/mirac/Downloads/HiperUFSC Dataset.xlsx")
View(HiperUFSC_Dataset)
dados<-HiperUFSC_Dataset
str(dados)
#Transformando Charac em Fator (Variáveis Categoricas)
dados$Item_Fat_Content <- factor(dados$Item_Fat_Content)
dados$Item_Type <- factor(dados$Item_Type)
dados$Outlet_Size <- factor(dados$Outlet_Size)
dados$Outlet_Location_Type <- factor(dados$Outlet_Location_Type)
dados$Outlet_Type <- factor(dados$Outlet_Type)
## Primeiro Trabalho: Estatistica Descritiva 
##Item identifier = nada a se fazer é apenas identificação


##variáveis qualitativas
summary.factor(dados$Item_Fat_Content)
summary.factor(dados$Item_Type)
summary.factor(dados$Outlet_Size)
summary.factor(dados$Outlet_Location_Type)
summary.factor(dados$Outlet_Type)

str(dados)
##Variaveis Quantitativas
 ##Item Weight, Item Visibility, Item MRP, Estabilishiment Year, Outlet Sales
  ##Obter medidas de dispersão e medias summary
summary(dados$Item_Weight)
sd(dados$Item_Weight, na.rm = TRUE)
var(dados$Item_Weight, na.rm = TRUE)

summary(dados$Item_Visibility)
sd(dados$Item_Visibility, na.rm = TRUE)
var(dados$Item_Visibility, na.rm = TRUE)

summary(dados$Item_MRP)
sd(dados$Item_MRP, na.rm = TRUE)
var(dados$Item_MRP, na.rm = TRUE)

summary(dados$Outlet_Establishment_Year)
sd(dados$Outlet_Establishment_Year, na.rm = TRUE)
var(dados$Outlet_Establishment_Year, na.rm = TRUE)

summary(dados$Item_Outlet_Sales)
sd(dados$Item_Outlet_Sales, na.rm = TRUE)
var(dados$Item_Outlet_Sales, na.rm = TRUE)

## Tabelas de Contigencia


##Exploração dos Dados por meio dos Gráficos

##Base

##Usado em variaveis Numericas
##Grafico de uma variável
##histograma
hist(dados$Item_Visibility)
hist(dados$Item_Weight)
hist(dados$Item_MRP)
hist(dados$Outlet_Establishment_Year)
hist(dados$Item_Outlet_Sales)
##grafico de densidade

##grafico Boxplot Analisar MRP Weight Outlet Sales EstabilishimentYear
boxplot(dados$Item_MRP)
boxplot(dados$Item_Weight)
boxplot(dados$Item_Outlet_Sales) ##demonstrou mais outliers (interessante)
boxplot(dados$Outlet_Establishment_Year)
##Grafico de Barras para variaveis categoricas fator
plot(dados$Item_Fat_Content)
plot(dados$Item_Type)
plot(dados$Item_Fat_Content)
## duas variaveis scatter plot num x num
plot(dados$Item_Outlet_Sales, dados$Item_Visibility)
##categorica x categorica 
##TIPO MOSAICO
plot(table(dados$Outlet_Location_Type, dados$Outlet_Size))
##NUMX CATEGORICA
plot(dados$Item_Type, dados$Item_Outlet_Sales )
##grafico multivariaveis usando ggplot








```

