data<-read_excel("C:/Users/mirac/Downloads/HiperUFSC Dataset.xlsx")
summary(data)
data$Item_Fat_Content <- factor(data$Item_Fat_Content)
data$Item_Type <- factor(data$Item_Type)
data$Outlet_Size <- factor(data$Outlet_Size)
data$Outlet_Location_Type <- factor(data$Outlet_Location_Type)
data$Outlet_Type <- factor(data$Outlet_Type)
str(data)
summary(data)
